---
title: "R Geospatial Cheatsheet"
author: "Patty Frontiera"
date: "2/12/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Read in, review, transform and plot geospatial data

<table border=1>
<tr>
<th>What</th><th>Examples of How</th>
</tr>
<tr>
<td> Load the libraries</td>
<td> 
```{r}
library(sp) # classes and methods for spatial data
library(rgdal)  # library for importing and exporting spatial data files
```
</td>
</tr>
<tr>
<td>Read in Shapefile</td>
<td>
```{r}
sf_boundary <- readOGR("./data", "sf_boundary")
```
</td>
</tr>
<tr>
<td>
Read in a CSV file of point data</td>
<td>
```{r}
bart_stations <- read.csv("./data/bart.csv")
head(bart_stations,2) # take a look
```
</td>
</tr>
<tr>
<td>Convert a data frame to a SpatialPointsDataFrame</td>
<td>
```{r}
coordinates(bart_stations) <- c("X", "Y")
```
</td>
</tr>
<tr>
<td>Get the CRS</td>
<td>
```{r}
proj4string(sf_boundary)
proj4string(bart_stations)
```
</td>
</tr>

<tr>
<td>
Set (define) the CRS
</td>
<td>
```{r}
proj4string(bart_stations) <- CRS("+init=epsg:4326") 
#
# or
#
#proj4string(landmarks) <- CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs") 
#                         
```
</td>
</tr>
<tr>
<td> Transform (reproject) the CRSs to match</td>
<td>
```{r}
bart_stations2 <- spTransform(bart_stations, CRS(proj4string(sf_boundary)))
#
# or
#
# bart_stations2 <- spTransform(landmarks, CRS("+init=epsg:26910"))
#
```

</td>
</tr>
<tr>
<td>
Make a quick plot of the data
</td>
<td>
```{r}
plot(sf_boundary)
points(bart_stations2)
```
</td>
</tr>

</table>
